language: java
dist: trusty
sudo: false
jdk:
  - oraclejdk8

#after_success:
#- ./gradlew codeCoverageReport --debug --info --stacktrace

after_failure:
- ./gradlew clean check --debug --info --stacktrace

notifications:
  slack:
    secure: 0Nf9Bk3lFW+35ifBhO25JnX23ZKUC+Eqo6YaRZ+6jQ8aKHHbPsf9DuaWX3+8C7pGzBTK0Ho7dNXVfNz4pYjrvv8b4rukKY6wEFSzMMJrCW0udRfHNEa3jj5VAm/BDXMypbzjkMm9XJ5aAPBUweb+oyHJBCWwNNCyHElQDp2TggE=
