site_name: GROBID Documentation
repo_url: https://github.com/kermitt2/grobid/
repo_name: GitHub
theme: ReadTheDocs
site_description: Documentation for GROBID
docs_dir: doc
include_search: true
pages:
- ['index.md', 'Home']
- ['Install-Grobid.md', 'Install GROBID']
- ['Grobid-service.md', 'Grobid service']
- ['Grobid-batch.md', 'Grobid batch mode']
- ['Grobid-java-library.md', 'Java library']
- ['References.md', 'References']
- ['License.md', 'License']
